#!/bin/bash

# combine multifiles line by line
paste file1.txt file2.txt > fileresults.txt

pr -tmJ a.txt b.txt > c.txt


# copy data between tmux-buffer with system clipboard
tmux show-buffer | xclip -sel clip -i
xclip -sel clip -o | xargs -0 tmux set-buffer


# extend screen when multi screens
xrandr --output VGA-0 --right-of LDVS-0 --auto
